### ISSUE TITLE
书妖，请问在candy中如何实现一键执行多命令，谢谢

### ISSUE THREAD

**Issue by valuex** [aamii/Candy#1]
书妖，
请问在candy中如何实现一键执行多命令，比如选中一个短文本，利用多个web搜索引擎进行搜索。

**Comment by aamii** [comment]
sorry，最近没上来过，才看到。
可以自己增加这样的指令，下一个版本，我准备把“指令部分的代码挪出来，用户可以按照一个规则自己添加指令，包括多命令”

**Comment by palesaint** [comment]
我足足等了三年😁
